/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ball {
  'ballNumber' : bigint,
  'runs' : bigint,
  'bowler' : Player,
  'isWicket' : boolean,
  'extras' : [] | [BallExtras],
  'batsman' : Player,
}
export interface BallExtras {
  'noBall' : boolean,
  'byes' : bigint,
  'wide' : boolean,
  'legByes' : bigint,
  'legalDelivery' : boolean,
}
export interface Innings {
  'overs' : [] | [bigint],
  'totalWickets' : bigint,
  'battingTeam' : Team,
  'totalRuns' : bigint,
  'bowlingTeam' : Team,
  'ballsInCurrentOver' : bigint,
  'balls' : Array<Ball>,
}
export interface Match {
  'id' : bigint,
  'teams' : Array<Team>,
  'owner' : Principal,
  'oversPerInnings' : [] | [bigint],
  'innings' : Array<Innings>,
}
export interface Player {
  'id' : bigint,
  'name' : string,
  'battingOrderPosition' : [] | [bigint],
}
export interface Team {
  'id' : bigint,
  'name' : string,
  'players' : Array<Player>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMatch' : ActorMethod<[Array<Team>, [] | [bigint]], bigint>,
  'deleteMatch' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatch' : ActorMethod<[bigint], [] | [Match]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMatches' : ActorMethod<[], Array<Match>>,
  'recordBall' : ActorMethod<[bigint, bigint, Ball], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startInnings' : ActorMethod<[bigint, Team, Team, [] | [bigint]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];