/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'battingOrderPosition' : IDL.Opt(IDL.Nat),
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'players' : IDL.Vec(Player),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const BallExtras = IDL.Record({
  'noBall' : IDL.Bool,
  'byes' : IDL.Nat,
  'wide' : IDL.Bool,
  'legByes' : IDL.Nat,
  'legalDelivery' : IDL.Bool,
});
export const Ball = IDL.Record({
  'ballNumber' : IDL.Nat,
  'runs' : IDL.Nat,
  'bowler' : Player,
  'isWicket' : IDL.Bool,
  'extras' : IDL.Opt(BallExtras),
  'batsman' : Player,
});
export const Innings = IDL.Record({
  'overs' : IDL.Opt(IDL.Nat),
  'totalWickets' : IDL.Nat,
  'battingTeam' : Team,
  'totalRuns' : IDL.Nat,
  'bowlingTeam' : Team,
  'ballsInCurrentOver' : IDL.Nat,
  'balls' : IDL.Vec(Ball),
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'teams' : IDL.Vec(Team),
  'owner' : IDL.Principal,
  'oversPerInnings' : IDL.Opt(IDL.Nat),
  'innings' : IDL.Vec(Innings),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMatch' : IDL.Func([IDL.Vec(Team), IDL.Opt(IDL.Nat)], [IDL.Nat], []),
  'deleteMatch' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'recordBall' : IDL.Func([IDL.Nat, IDL.Nat, Ball], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startInnings' : IDL.Func([IDL.Nat, Team, Team, IDL.Opt(IDL.Nat)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'battingOrderPosition' : IDL.Opt(IDL.Nat),
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'players' : IDL.Vec(Player),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const BallExtras = IDL.Record({
    'noBall' : IDL.Bool,
    'byes' : IDL.Nat,
    'wide' : IDL.Bool,
    'legByes' : IDL.Nat,
    'legalDelivery' : IDL.Bool,
  });
  const Ball = IDL.Record({
    'ballNumber' : IDL.Nat,
    'runs' : IDL.Nat,
    'bowler' : Player,
    'isWicket' : IDL.Bool,
    'extras' : IDL.Opt(BallExtras),
    'batsman' : Player,
  });
  const Innings = IDL.Record({
    'overs' : IDL.Opt(IDL.Nat),
    'totalWickets' : IDL.Nat,
    'battingTeam' : Team,
    'totalRuns' : IDL.Nat,
    'bowlingTeam' : Team,
    'ballsInCurrentOver' : IDL.Nat,
    'balls' : IDL.Vec(Ball),
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'teams' : IDL.Vec(Team),
    'owner' : IDL.Principal,
    'oversPerInnings' : IDL.Opt(IDL.Nat),
    'innings' : IDL.Vec(Innings),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMatch' : IDL.Func([IDL.Vec(Team), IDL.Opt(IDL.Nat)], [IDL.Nat], []),
    'deleteMatch' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'recordBall' : IDL.Func([IDL.Nat, IDL.Nat, Ball], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startInnings' : IDL.Func([IDL.Nat, Team, Team, IDL.Opt(IDL.Nat)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };