/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: bigint;
    name: string;
    battingOrderPosition?: bigint;
}
export interface PersistentPlayerStats {
    bowlingStats: BowlingStats;
    battingStats: BattingStats;
    lastUpdated: Time;
    playerName: string;
    matchesPlayed: bigint;
}
export type Time = bigint;
export interface SavedTeam {
    owner: Principal;
    createdAt: Time;
    team: Team;
    updatedAt: Time;
}
export interface BattingStats {
    fours: bigint;
    outs: bigint;
    runs: bigint;
    sixes: bigint;
    ballsFaced: bigint;
}
export interface Ball {
    ballNumber: bigint;
    previousStrikerState?: PlayerStatsSnapshot;
    previousNonStrikerState?: PlayerStatsSnapshot;
    runs: bigint;
    bowler: Player;
    isWicket: boolean;
    extras?: BallExtras;
    batsman: Player;
}
export interface BowlingStats {
    maidens: bigint;
    wickets: bigint;
    ballsBowled: bigint;
    runsConceded: bigint;
}
export interface Match {
    id: bigint;
    teams: Array<Team>;
    owner: Principal;
    oversPerInnings?: bigint;
    toss?: TossInfo;
    innings: Array<Innings>;
}
export interface TossInfo {
    decision: TossDecision;
    winnerTeamId: bigint;
}
export interface PlayerStatsSnapshot {
    fours: bigint;
    player: Player;
    runs: bigint;
    sixes: bigint;
    ballsFaced: bigint;
    isStriker: boolean;
}
export interface BallExtras {
    noBall: boolean;
    byes: bigint;
    wide: boolean;
    legByes: bigint;
    legalDelivery: boolean;
}
export interface Innings {
    currentStriker?: Player;
    overs?: bigint;
    totalWickets: bigint;
    battingTeam: Team;
    currentNonStriker?: Player;
    currentBowler?: Player;
    totalRuns: bigint;
    bowlingTeam: Team;
    ballsInCurrentOver: bigint;
    balls: Array<Ball>;
}
export interface UserProfile {
    name: string;
}
export interface Team {
    id: bigint;
    name: string;
    players: Array<Player>;
}
export enum TossDecision {
    bat = "bat",
    bowl = "bowl"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMatch(teams: Array<Team>, oversPerInnings: bigint | null, toss: TossInfo | null): Promise<bigint>;
    deleteMatch(matchId: bigint): Promise<void>;
    getCallerSavedTeam(): Promise<SavedTeam | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMatch(matchId: bigint): Promise<Match | null>;
    getPlayerStats(playerName: string): Promise<PersistentPlayerStats | null>;
    getSavedTeamOf(user: Principal): Promise<SavedTeam | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllPlayerStats(): Promise<Array<PersistentPlayerStats>>;
    listMatches(): Promise<Array<Match>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveTeam(team: Team): Promise<void>;
    startSecondInnings(matchId: bigint, newInnings: Innings): Promise<void>;
    updatePlayerStats(playerName: string, batting: BattingStats, bowling: BowlingStats): Promise<void>;
    updateTossInfo(matchId: bigint, toss: TossInfo): Promise<void>;
}
import type { Ball as _Ball, BallExtras as _BallExtras, Innings as _Innings, Match as _Match, PersistentPlayerStats as _PersistentPlayerStats, Player as _Player, PlayerStatsSnapshot as _PlayerStatsSnapshot, SavedTeam as _SavedTeam, Team as _Team, Time as _Time, TossDecision as _TossDecision, TossInfo as _TossInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMatch(arg0: Array<Team>, arg1: bigint | null, arg2: TossInfo | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteMatch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatch(arg0);
            return result;
        }
    }
    async getCallerSavedTeam(): Promise<SavedTeam | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerSavedTeam();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerSavedTeam();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: bigint): Promise<Match | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerStats(arg0: string): Promise<PersistentPlayerStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerStats(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerStats(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavedTeamOf(arg0: Principal): Promise<SavedTeam | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedTeamOf(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedTeamOf(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllPlayerStats(): Promise<Array<PersistentPlayerStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPlayerStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPlayerStats();
            return result;
        }
    }
    async listMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMatches();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMatches();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveTeam(arg0: Team): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTeam(to_candid_Team_n4(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTeam(to_candid_Team_n4(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async startSecondInnings(arg0: bigint, arg1: Innings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startSecondInnings(arg0, to_candid_Innings_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSecondInnings(arg0, to_candid_Innings_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePlayerStats(arg0: string, arg1: BattingStats, arg2: BowlingStats): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayerStats(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayerStats(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTossInfo(arg0: bigint, arg1: TossInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTossInfo(arg0, to_candid_TossInfo_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTossInfo(arg0, to_candid_TossInfo_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Ball_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ball): Ball {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Innings_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Innings): Innings {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerStatsSnapshot_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerStatsSnapshot): PlayerStatsSnapshot {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SavedTeam_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SavedTeam): SavedTeam {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TossDecision_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TossDecision): TossDecision {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_TossInfo_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TossInfo): TossInfo {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SavedTeam]): SavedTeam | null {
    return value.length === 0 ? null : from_candid_SavedTeam_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Match]): Match | null {
    return value.length === 0 ? null : from_candid_Match_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TossInfo]): TossInfo | null {
    return value.length === 0 ? null : from_candid_TossInfo_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Player]): Player | null {
    return value.length === 0 ? null : from_candid_Player_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerStatsSnapshot]): PlayerStatsSnapshot | null {
    return value.length === 0 ? null : from_candid_PlayerStatsSnapshot_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BallExtras]): BallExtras | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersistentPlayerStats]): PersistentPlayerStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    createdAt: _Time;
    team: _Team;
    updatedAt: _Time;
}): {
    owner: Principal;
    createdAt: Time;
    team: Team;
    updatedAt: Time;
} {
    return {
        owner: value.owner,
        createdAt: value.createdAt,
        team: from_candid_Team_n18(_uploadFile, _downloadFile, value.team),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    players: Array<_Player>;
}): {
    id: bigint;
    name: string;
    players: Array<Player>;
} {
    return {
        id: value.id,
        name: value.name,
        players: from_candid_vec_n20(_uploadFile, _downloadFile, value.players)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    battingOrderPosition: [] | [bigint];
}): {
    id: bigint;
    name: string;
    battingOrderPosition?: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        battingOrderPosition: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.battingOrderPosition))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    teams: Array<_Team>;
    owner: Principal;
    oversPerInnings: [] | [bigint];
    toss: [] | [_TossInfo];
    innings: Array<_Innings>;
}): {
    id: bigint;
    teams: Array<Team>;
    owner: Principal;
    oversPerInnings?: bigint;
    toss?: TossInfo;
    innings: Array<Innings>;
} {
    return {
        id: value.id,
        teams: from_candid_vec_n30(_uploadFile, _downloadFile, value.teams),
        owner: value.owner,
        oversPerInnings: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.oversPerInnings)),
        toss: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.toss)),
        innings: from_candid_vec_n36(_uploadFile, _downloadFile, value.innings)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    decision: _TossDecision;
    winnerTeamId: bigint;
}): {
    decision: TossDecision;
    winnerTeamId: bigint;
} {
    return {
        decision: from_candid_TossDecision_n34(_uploadFile, _downloadFile, value.decision),
        winnerTeamId: value.winnerTeamId
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentStriker: [] | [_Player];
    overs: [] | [bigint];
    totalWickets: bigint;
    battingTeam: _Team;
    currentNonStriker: [] | [_Player];
    currentBowler: [] | [_Player];
    totalRuns: bigint;
    bowlingTeam: _Team;
    ballsInCurrentOver: bigint;
    balls: Array<_Ball>;
}): {
    currentStriker?: Player;
    overs?: bigint;
    totalWickets: bigint;
    battingTeam: Team;
    currentNonStriker?: Player;
    currentBowler?: Player;
    totalRuns: bigint;
    bowlingTeam: Team;
    ballsInCurrentOver: bigint;
    balls: Array<Ball>;
} {
    return {
        currentStriker: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.currentStriker)),
        overs: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.overs)),
        totalWickets: value.totalWickets,
        battingTeam: from_candid_Team_n18(_uploadFile, _downloadFile, value.battingTeam),
        currentNonStriker: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.currentNonStriker)),
        currentBowler: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.currentBowler)),
        totalRuns: value.totalRuns,
        bowlingTeam: from_candid_Team_n18(_uploadFile, _downloadFile, value.bowlingTeam),
        ballsInCurrentOver: value.ballsInCurrentOver,
        balls: from_candid_vec_n40(_uploadFile, _downloadFile, value.balls)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ballNumber: bigint;
    previousStrikerState: [] | [_PlayerStatsSnapshot];
    previousNonStrikerState: [] | [_PlayerStatsSnapshot];
    runs: bigint;
    bowler: _Player;
    isWicket: boolean;
    extras: [] | [_BallExtras];
    batsman: _Player;
}): {
    ballNumber: bigint;
    previousStrikerState?: PlayerStatsSnapshot;
    previousNonStrikerState?: PlayerStatsSnapshot;
    runs: bigint;
    bowler: Player;
    isWicket: boolean;
    extras?: BallExtras;
    batsman: Player;
} {
    return {
        ballNumber: value.ballNumber,
        previousStrikerState: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.previousStrikerState)),
        previousNonStrikerState: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.previousNonStrikerState)),
        runs: value.runs,
        bowler: from_candid_Player_n21(_uploadFile, _downloadFile, value.bowler),
        isWicket: value.isWicket,
        extras: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.extras)),
        batsman: from_candid_Player_n21(_uploadFile, _downloadFile, value.batsman)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fours: bigint;
    player: _Player;
    runs: bigint;
    sixes: bigint;
    ballsFaced: bigint;
    isStriker: boolean;
}): {
    fours: bigint;
    player: Player;
    runs: bigint;
    sixes: bigint;
    ballsFaced: bigint;
    isStriker: boolean;
} {
    return {
        fours: value.fours,
        player: from_candid_Player_n21(_uploadFile, _downloadFile, value.player),
        runs: value.runs,
        sixes: value.sixes,
        ballsFaced: value.ballsFaced,
        isStriker: value.isStriker
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bat: null;
} | {
    bowl: null;
}): TossDecision {
    return "bat" in value ? TossDecision.bat : "bowl" in value ? TossDecision.bowl : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Team>): Array<Team> {
    return value.map((x)=>from_candid_Team_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Innings>): Array<Innings> {
    return value.map((x)=>from_candid_Innings_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ball>): Array<Ball> {
    return value.map((x)=>from_candid_Ball_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n28(_uploadFile, _downloadFile, x));
}
function to_candid_Ball_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Ball): _Ball {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_Innings_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Innings): _Innings {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_PlayerStatsSnapshot_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerStatsSnapshot): _PlayerStatsSnapshot {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_Player_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Player): _Player {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Team_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Team): _Team {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_TossDecision_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TossDecision): _TossDecision {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_TossInfo_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TossInfo): _TossInfo {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TossInfo | null): [] | [_TossInfo] {
    return value === null ? candid_none() : candid_some(to_candid_TossInfo_n11(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    decision: TossDecision;
    winnerTeamId: bigint;
}): {
    decision: _TossDecision;
    winnerTeamId: bigint;
} {
    return {
        decision: to_candid_TossDecision_n13(_uploadFile, _downloadFile, value.decision),
        winnerTeamId: value.winnerTeamId
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    players: Array<Player>;
}): {
    id: bigint;
    name: string;
    players: Array<_Player>;
} {
    return {
        id: value.id,
        name: value.name,
        players: to_candid_vec_n6(_uploadFile, _downloadFile, value.players)
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentStriker?: Player;
    overs?: bigint;
    totalWickets: bigint;
    battingTeam: Team;
    currentNonStriker?: Player;
    currentBowler?: Player;
    totalRuns: bigint;
    bowlingTeam: Team;
    ballsInCurrentOver: bigint;
    balls: Array<Ball>;
}): {
    currentStriker: [] | [_Player];
    overs: [] | [bigint];
    totalWickets: bigint;
    battingTeam: _Team;
    currentNonStriker: [] | [_Player];
    currentBowler: [] | [_Player];
    totalRuns: bigint;
    bowlingTeam: _Team;
    ballsInCurrentOver: bigint;
    balls: Array<_Ball>;
} {
    return {
        currentStriker: value.currentStriker ? candid_some(to_candid_Player_n7(_uploadFile, _downloadFile, value.currentStriker)) : candid_none(),
        overs: value.overs ? candid_some(value.overs) : candid_none(),
        totalWickets: value.totalWickets,
        battingTeam: to_candid_Team_n4(_uploadFile, _downloadFile, value.battingTeam),
        currentNonStriker: value.currentNonStriker ? candid_some(to_candid_Player_n7(_uploadFile, _downloadFile, value.currentNonStriker)) : candid_none(),
        currentBowler: value.currentBowler ? candid_some(to_candid_Player_n7(_uploadFile, _downloadFile, value.currentBowler)) : candid_none(),
        totalRuns: value.totalRuns,
        bowlingTeam: to_candid_Team_n4(_uploadFile, _downloadFile, value.bowlingTeam),
        ballsInCurrentOver: value.ballsInCurrentOver,
        balls: to_candid_vec_n51(_uploadFile, _downloadFile, value.balls)
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ballNumber: bigint;
    previousStrikerState?: PlayerStatsSnapshot;
    previousNonStrikerState?: PlayerStatsSnapshot;
    runs: bigint;
    bowler: Player;
    isWicket: boolean;
    extras?: BallExtras;
    batsman: Player;
}): {
    ballNumber: bigint;
    previousStrikerState: [] | [_PlayerStatsSnapshot];
    previousNonStrikerState: [] | [_PlayerStatsSnapshot];
    runs: bigint;
    bowler: _Player;
    isWicket: boolean;
    extras: [] | [_BallExtras];
    batsman: _Player;
} {
    return {
        ballNumber: value.ballNumber,
        previousStrikerState: value.previousStrikerState ? candid_some(to_candid_PlayerStatsSnapshot_n54(_uploadFile, _downloadFile, value.previousStrikerState)) : candid_none(),
        previousNonStrikerState: value.previousNonStrikerState ? candid_some(to_candid_PlayerStatsSnapshot_n54(_uploadFile, _downloadFile, value.previousNonStrikerState)) : candid_none(),
        runs: value.runs,
        bowler: to_candid_Player_n7(_uploadFile, _downloadFile, value.bowler),
        isWicket: value.isWicket,
        extras: value.extras ? candid_some(value.extras) : candid_none(),
        batsman: to_candid_Player_n7(_uploadFile, _downloadFile, value.batsman)
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fours: bigint;
    player: Player;
    runs: bigint;
    sixes: bigint;
    ballsFaced: bigint;
    isStriker: boolean;
}): {
    fours: bigint;
    player: _Player;
    runs: bigint;
    sixes: bigint;
    ballsFaced: bigint;
    isStriker: boolean;
} {
    return {
        fours: value.fours,
        player: to_candid_Player_n7(_uploadFile, _downloadFile, value.player),
        runs: value.runs,
        sixes: value.sixes,
        ballsFaced: value.ballsFaced,
        isStriker: value.isStriker
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    battingOrderPosition?: bigint;
}): {
    id: bigint;
    name: string;
    battingOrderPosition: [] | [bigint];
} {
    return {
        id: value.id,
        name: value.name,
        battingOrderPosition: value.battingOrderPosition ? candid_some(value.battingOrderPosition) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TossDecision): {
    bat: null;
} | {
    bowl: null;
} {
    return value == TossDecision.bat ? {
        bat: null
    } : value == TossDecision.bowl ? {
        bowl: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Team>): Array<_Team> {
    return value.map((x)=>to_candid_Team_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Ball>): Array<_Ball> {
    return value.map((x)=>to_candid_Ball_n52(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Player>): Array<_Player> {
    return value.map((x)=>to_candid_Player_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
