/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'battingOrderPosition' : IDL.Opt(IDL.Nat),
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'players' : IDL.Vec(Player),
});
export const TossDecision = IDL.Variant({
  'bat' : IDL.Null,
  'bowl' : IDL.Null,
});
export const TossInfo = IDL.Record({
  'decision' : TossDecision,
  'winnerTeamId' : IDL.Nat,
});
export const Time = IDL.Int;
export const SavedTeam = IDL.Record({
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'team' : Team,
  'updatedAt' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PlayerStatsSnapshot = IDL.Record({
  'fours' : IDL.Nat,
  'player' : Player,
  'runs' : IDL.Nat,
  'sixes' : IDL.Nat,
  'ballsFaced' : IDL.Nat,
  'isStriker' : IDL.Bool,
});
export const BallExtras = IDL.Record({
  'noBall' : IDL.Bool,
  'byes' : IDL.Nat,
  'wide' : IDL.Bool,
  'legByes' : IDL.Nat,
  'legalDelivery' : IDL.Bool,
});
export const Ball = IDL.Record({
  'ballNumber' : IDL.Nat,
  'previousStrikerState' : IDL.Opt(PlayerStatsSnapshot),
  'previousNonStrikerState' : IDL.Opt(PlayerStatsSnapshot),
  'runs' : IDL.Nat,
  'bowler' : Player,
  'isWicket' : IDL.Bool,
  'extras' : IDL.Opt(BallExtras),
  'batsman' : Player,
});
export const Innings = IDL.Record({
  'currentStriker' : IDL.Opt(Player),
  'overs' : IDL.Opt(IDL.Nat),
  'totalWickets' : IDL.Nat,
  'battingTeam' : Team,
  'currentNonStriker' : IDL.Opt(Player),
  'currentBowler' : IDL.Opt(Player),
  'totalRuns' : IDL.Nat,
  'bowlingTeam' : Team,
  'ballsInCurrentOver' : IDL.Nat,
  'balls' : IDL.Vec(Ball),
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'teams' : IDL.Vec(Team),
  'owner' : IDL.Principal,
  'oversPerInnings' : IDL.Opt(IDL.Nat),
  'toss' : IDL.Opt(TossInfo),
  'innings' : IDL.Vec(Innings),
});
export const BowlingStats = IDL.Record({
  'maidens' : IDL.Nat,
  'wickets' : IDL.Nat,
  'ballsBowled' : IDL.Nat,
  'runsConceded' : IDL.Nat,
});
export const BattingStats = IDL.Record({
  'fours' : IDL.Nat,
  'outs' : IDL.Nat,
  'runs' : IDL.Nat,
  'sixes' : IDL.Nat,
  'ballsFaced' : IDL.Nat,
});
export const PersistentPlayerStats = IDL.Record({
  'bowlingStats' : BowlingStats,
  'battingStats' : BattingStats,
  'lastUpdated' : Time,
  'playerName' : IDL.Text,
  'matchesPlayed' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMatch' : IDL.Func(
      [IDL.Vec(Team), IDL.Opt(IDL.Nat), IDL.Opt(TossInfo)],
      [IDL.Nat],
      [],
    ),
  'deleteMatch' : IDL.Func([IDL.Nat], [], []),
  'getCallerSavedTeam' : IDL.Func([], [IDL.Opt(SavedTeam)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
  'getPlayerStats' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PersistentPlayerStats)],
      ['query'],
    ),
  'getSavedTeamOf' : IDL.Func([IDL.Principal], [IDL.Opt(SavedTeam)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllPlayerStats' : IDL.Func(
      [],
      [IDL.Vec(PersistentPlayerStats)],
      ['query'],
    ),
  'listMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTeam' : IDL.Func([Team], [], []),
  'startSecondInnings' : IDL.Func([IDL.Nat, Innings], [], []),
  'updatePlayerStats' : IDL.Func(
      [IDL.Text, BattingStats, BowlingStats],
      [],
      [],
    ),
  'updateTossInfo' : IDL.Func([IDL.Nat, TossInfo], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'battingOrderPosition' : IDL.Opt(IDL.Nat),
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'players' : IDL.Vec(Player),
  });
  const TossDecision = IDL.Variant({ 'bat' : IDL.Null, 'bowl' : IDL.Null });
  const TossInfo = IDL.Record({
    'decision' : TossDecision,
    'winnerTeamId' : IDL.Nat,
  });
  const Time = IDL.Int;
  const SavedTeam = IDL.Record({
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'team' : Team,
    'updatedAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PlayerStatsSnapshot = IDL.Record({
    'fours' : IDL.Nat,
    'player' : Player,
    'runs' : IDL.Nat,
    'sixes' : IDL.Nat,
    'ballsFaced' : IDL.Nat,
    'isStriker' : IDL.Bool,
  });
  const BallExtras = IDL.Record({
    'noBall' : IDL.Bool,
    'byes' : IDL.Nat,
    'wide' : IDL.Bool,
    'legByes' : IDL.Nat,
    'legalDelivery' : IDL.Bool,
  });
  const Ball = IDL.Record({
    'ballNumber' : IDL.Nat,
    'previousStrikerState' : IDL.Opt(PlayerStatsSnapshot),
    'previousNonStrikerState' : IDL.Opt(PlayerStatsSnapshot),
    'runs' : IDL.Nat,
    'bowler' : Player,
    'isWicket' : IDL.Bool,
    'extras' : IDL.Opt(BallExtras),
    'batsman' : Player,
  });
  const Innings = IDL.Record({
    'currentStriker' : IDL.Opt(Player),
    'overs' : IDL.Opt(IDL.Nat),
    'totalWickets' : IDL.Nat,
    'battingTeam' : Team,
    'currentNonStriker' : IDL.Opt(Player),
    'currentBowler' : IDL.Opt(Player),
    'totalRuns' : IDL.Nat,
    'bowlingTeam' : Team,
    'ballsInCurrentOver' : IDL.Nat,
    'balls' : IDL.Vec(Ball),
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'teams' : IDL.Vec(Team),
    'owner' : IDL.Principal,
    'oversPerInnings' : IDL.Opt(IDL.Nat),
    'toss' : IDL.Opt(TossInfo),
    'innings' : IDL.Vec(Innings),
  });
  const BowlingStats = IDL.Record({
    'maidens' : IDL.Nat,
    'wickets' : IDL.Nat,
    'ballsBowled' : IDL.Nat,
    'runsConceded' : IDL.Nat,
  });
  const BattingStats = IDL.Record({
    'fours' : IDL.Nat,
    'outs' : IDL.Nat,
    'runs' : IDL.Nat,
    'sixes' : IDL.Nat,
    'ballsFaced' : IDL.Nat,
  });
  const PersistentPlayerStats = IDL.Record({
    'bowlingStats' : BowlingStats,
    'battingStats' : BattingStats,
    'lastUpdated' : Time,
    'playerName' : IDL.Text,
    'matchesPlayed' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMatch' : IDL.Func(
        [IDL.Vec(Team), IDL.Opt(IDL.Nat), IDL.Opt(TossInfo)],
        [IDL.Nat],
        [],
      ),
    'deleteMatch' : IDL.Func([IDL.Nat], [], []),
    'getCallerSavedTeam' : IDL.Func([], [IDL.Opt(SavedTeam)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
    'getPlayerStats' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PersistentPlayerStats)],
        ['query'],
      ),
    'getSavedTeamOf' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SavedTeam)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllPlayerStats' : IDL.Func(
        [],
        [IDL.Vec(PersistentPlayerStats)],
        ['query'],
      ),
    'listMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTeam' : IDL.Func([Team], [], []),
    'startSecondInnings' : IDL.Func([IDL.Nat, Innings], [], []),
    'updatePlayerStats' : IDL.Func(
        [IDL.Text, BattingStats, BowlingStats],
        [],
        [],
      ),
    'updateTossInfo' : IDL.Func([IDL.Nat, TossInfo], [], []),
  });
};

export const init = ({ IDL }) => { return []; };