/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ball {
  'ballNumber' : bigint,
  'previousStrikerState' : [] | [PlayerStatsSnapshot],
  'previousNonStrikerState' : [] | [PlayerStatsSnapshot],
  'runs' : bigint,
  'bowler' : Player,
  'isWicket' : boolean,
  'extras' : [] | [BallExtras],
  'batsman' : Player,
}
export interface BallExtras {
  'noBall' : boolean,
  'byes' : bigint,
  'wide' : boolean,
  'legByes' : bigint,
  'legalDelivery' : boolean,
}
export interface BattingStats {
  'fours' : bigint,
  'outs' : bigint,
  'runs' : bigint,
  'sixes' : bigint,
  'ballsFaced' : bigint,
}
export interface BowlingStats {
  'maidens' : bigint,
  'wickets' : bigint,
  'ballsBowled' : bigint,
  'runsConceded' : bigint,
}
export interface Innings {
  'currentStriker' : [] | [Player],
  'overs' : [] | [bigint],
  'totalWickets' : bigint,
  'battingTeam' : Team,
  'currentNonStriker' : [] | [Player],
  'currentBowler' : [] | [Player],
  'totalRuns' : bigint,
  'bowlingTeam' : Team,
  'ballsInCurrentOver' : bigint,
  'balls' : Array<Ball>,
}
export interface Match {
  'id' : bigint,
  'teams' : Array<Team>,
  'owner' : Principal,
  'oversPerInnings' : [] | [bigint],
  'toss' : [] | [TossInfo],
  'innings' : Array<Innings>,
}
export interface PersistentPlayerStats {
  'bowlingStats' : BowlingStats,
  'battingStats' : BattingStats,
  'lastUpdated' : Time,
  'playerName' : string,
  'matchesPlayed' : bigint,
}
export interface Player {
  'id' : bigint,
  'name' : string,
  'battingOrderPosition' : [] | [bigint],
}
export interface PlayerStatsSnapshot {
  'fours' : bigint,
  'player' : Player,
  'runs' : bigint,
  'sixes' : bigint,
  'ballsFaced' : bigint,
  'isStriker' : boolean,
}
export interface SavedTeam {
  'owner' : Principal,
  'createdAt' : Time,
  'team' : Team,
  'updatedAt' : Time,
}
export interface Team {
  'id' : bigint,
  'name' : string,
  'players' : Array<Player>,
}
export type Time = bigint;
export type TossDecision = { 'bat' : null } |
  { 'bowl' : null };
export interface TossInfo { 'decision' : TossDecision, 'winnerTeamId' : bigint }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMatch' : ActorMethod<
    [Array<Team>, [] | [bigint], [] | [TossInfo]],
    bigint
  >,
  'deleteMatch' : ActorMethod<[bigint], undefined>,
  'getCallerSavedTeam' : ActorMethod<[], [] | [SavedTeam]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatch' : ActorMethod<[bigint], [] | [Match]>,
  'getPlayerStats' : ActorMethod<[string], [] | [PersistentPlayerStats]>,
  'getSavedTeamOf' : ActorMethod<[Principal], [] | [SavedTeam]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllPlayerStats' : ActorMethod<[], Array<PersistentPlayerStats>>,
  'listMatches' : ActorMethod<[], Array<Match>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveTeam' : ActorMethod<[Team], undefined>,
  'startSecondInnings' : ActorMethod<[bigint, Innings], undefined>,
  'updatePlayerStats' : ActorMethod<
    [string, BattingStats, BowlingStats],
    undefined
  >,
  'updateTossInfo' : ActorMethod<[bigint, TossInfo], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];